arpegio/blog/urls.py
"""Urls for the blog app."""
from django.conf.urls import url

from .views import PostDetail, PostList


app_name = 'blog'  # pylint: disable=invalid-name

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog',
        ),
    url(r'page/(?P<page>[\d])/$',
        PostList.as_view(),
        name='blog',
        ),
    url(r'^post/(?P<slug>[\w\d-]+)/$',
        PostDetail.as_view(),
        name='post'
        ),
]

urls.py
"""URL Configuration."""
from django.conf.urls import url, include

urlpatterns = [
    url(r'^blog/', include('arpegio.blog.urls',
                           namespace='blog',
                           app_name='blog'
                           )
        ),
    url(r'^pages/', include('arpegio.pages.urls',
                            namespace='pages',
                            app_name='pages'
                            )
        ),
    url(r'^category/', include('arpegio.categories.urls',
                               namespace='categories',
                               app_name='categories'
                               )
        ),
    url(r'^tags/', include('arpegio.tags.urls',
                           namespace='tags',
                           app_name='tags'
                           )
        ),
]

arpegio/blog/models.py
"""Blog models."""
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models

from arpegio.core.models import ContentMixin, Timestampable
from .managers import PostManager


class Post(ContentMixin,  # pylint: disable=model-missing-unicode
           Timestampable,
           models.Model):
    """Post Model."""

    STATUS_CHOICES = (('D', 'Draft'),
                      ('PB', 'Public'),
                      ('PV', 'Private'),
                      ('T', 'Trash'),
                      )

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE
                               )
    excerpt = models.TextField(blank=True, null=True)
    featured_image = models.ImageField(upload_to='post_covers',
                                       blank=True,
                                       null=True
                                       )
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    sticky = models.BooleanField(default=False)

    objects = PostManager()

    def get_absolute_url(self):
        """Get the absolute url of a post"""
        return reverse('blog:post', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-creation_date']

arpegio/blog/views.py
"""Views for the blog app."""
from itertools import chain
from django.views.generic.detail import DetailView
from django.views.generic import ListView

from .models import Post


class PostList(ListView):
    """Post list view."""
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        return list(chain(self.model.objects.sticky(),
                          self.model.objects.public()
                          ))

    def get_paginate_by(self, queryset):
        number_of_post = super(PostList, self).get_paginate_by(queryset)
        return number_of_post or 5

    def get_template_names(self):
        names = super(PostList, self).get_template_names()
        names.append('arpegio-blog/post_list.html')
        return names


class PostDetail(DetailView):
    """Post detail view."""
    model = Post

    def get_template_names(self):
        names = super(PostDetail, self).get_template_names()
        names.append('arpegio-blog/post_detail.html')
        return names

arpegio/blog/templates/arpegio-blog/post_detail.html
{% extends 'arpegio-core/base.html' %}

{% block head %}
  {% with title=post.title %}
    {{ block.super }}
  {% endwith %}
{% endblock %}

{% block content %}
<div>
  <h2>{{ post.title }}</h2>
  <p>{{ post.creation_date.date }} by {{ post.author }}</p>
  <div>
    {{ post.content }}
  </div>
</div>
{% endblock %}

arpegio/blog/templates/arpegio-blog/post_list.html
{% extends 'arpegio-core/base.html' %}

{% block content %}
<div>
  {% include 'arpegio-blog/includes/posts_list.html' with posts=posts %}
  {% if is_paginated %}
    <nav>
      <ul>
        {% if page_obj.has_previous %}
          <li>
            <a href="{% url 'blog:blog' page=page_obj.previous_page_number %}">
              Previous
            </a>
          </li>
        {% endif %}
        {% if page_obj.has_next %}
          <li>
            <a href="{% url 'blog:blog' page=page_obj.next_page_number %}">
              Next
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
</div>
{% endblock %}